// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ssNNEX-Vz9dziR--cg7wQq5yKe9bvAo',
    appId: '1:3868313034:ios:65336a28f950e59121fb33',
    messagingSenderId: '3868313034',
    projectId: 'yeidaraah',
    storageBucket: 'yeidaraah.firebasestorage.app',
    iosBundleId: 'com.example.yeidaraahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ssNNEX-Vz9dziR--cg7wQq5yKe9bvAo',
    appId: '1:3868313034:ios:65336a28f950e59121fb33',
    messagingSenderId: '3868313034',
    projectId: 'yeidaraah',
    storageBucket: 'yeidaraah.firebasestorage.app',
    iosBundleId: 'com.example.yeidaraahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnzxxQAB7gaCrRTdIyMbTOwcRtQDyWZ4M',
    appId: '1:3868313034:web:e4be02feea2e694921fb33',
    messagingSenderId: '3868313034',
    projectId: 'yeidaraah',
    authDomain: 'yeidaraah.firebaseapp.com',
    storageBucket: 'yeidaraah.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzxxQAB7gaCrRTdIyMbTOwcRtQDyWZ4M',
    appId: '1:3868313034:web:065788c33d8dc8dc21fb33',
    messagingSenderId: '3868313034',
    projectId: 'yeidaraah',
    authDomain: 'yeidaraah.firebaseapp.com',
    storageBucket: 'yeidaraah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOBfxa_Lr43ItO6pNoXROhAHeiubju4c',
    appId: '1:3868313034:android:68d4f9cf0a8f642721fb33',
    messagingSenderId: '3868313034',
    projectId: 'yeidaraah',
    storageBucket: 'yeidaraah.firebasestorage.app',
  );

}